name: CI
on:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published, created, edited ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fail-fast: false
        platform: ["esp32:esp32", "esp8266:esp8266"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.platform }}
          platforms: |
            - name: "esp32:esp32"
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: "esp8266:esp8266"
          libraries: |
            - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
            - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            - source-url: https://github.com/Links2004/XPT2046.git
            - source-url: https://github.com/Links2004/Adafruit_ILI9341.git
            - source-url: https://github.com/Bodmer/TFT_eSPI.git
            - source-url: https://github.com/lovyan03/LovyanGFX.git
